id: A9EF469EE
title: 'Declaration of the Power of Truth: A Prayer to Overcome Invading Forces'
type: translation
pechas:
- IFC9F1FAC
- IF9429445
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:07:06.980197
  last_modified_at: 2023-01-04 12:07:06.980207
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  IFC9F1FAC/148D: C5B7
  IF9429445/468F: C5B7
